### ISSUE TITLE
What is the file icon of atom editor screenshot?

### ISSUE THREAD

**Issue by ghsgz** [ahmad2smile/OneDark-Chester-Theme-VS2015#2]
![](https://cloud.githubusercontent.com/assets/6108922/14466134/f8931352-00ee-11e6-923a-682a79873032.PNG?raw=true)

The file icon looks awsome, but I cannot find it in atom packages or atom-chester-theme related repos. Thanks!

**Comment by ahmad2smile** [comment]
I only ported the color scheme, and I think Icons were default icons for Atom back then not sure not.

**Comment by ghsgz** [comment]
Thanks for your reply! I just found perhaps it is the graystyle version of [material icons pack](https://github.com/PKief/vscode-material-icon-theme) on Atom port.
